#
# Global config
#
AllCops:
  Exclude:
    - bin/*
  TargetRubyVersion: 2.6

require:
  - rubocop-rspec
  - rubocop-performance

#
# Cop-specific config
#
Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/BlockLength:
  ExcludedMethods: ['context', 'describe']

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
